### PR TITLE
chore/register-profile-data

### PR DESCRIPTION
**Pull request by kdluong**
# Notes

Now requires user to input basic user info when registering.

# Done Criteria

- [ ] No errors while navigating UI
- [ ] Document utils and api functions

# Testing

Hand tested: Clicked through UI, no errors

### CODE REVIEW

**Review by zacktraczyk — CHANGES_REQUESTED** [review]
Looks great! Only a few things that need some tweaking and it'll be perfect. First, the keyboard avoiding view/ scroll view don't seem to work, so you can't scroll down to all the entries or hit submit on the mobile tester, and the keyboard doesn't push the inputs up so you can see what you're typing. Additionally, I tried making an account an it gave an error as `[object object]` this was probably my error from when I first made this template code but it would be great if it displayed an clearer error messge.

**Comment by kdluong** [comment]
> 

Just fixed.

**Review by thegunner686 — CHANGES_REQUESTED** [review]
Something is up with the password validation. It will error out and freeze up so I can't edit the text inputs, and simultaneously say the password is strong but invalid.

Screen Shot 2023-03-12 at 11 34 25 PM

**Review by thegunner686 — APPROVED** [review]

**Review by zacktraczyk — APPROVED** [review]
Superb

**Pull request merged**
